<?php
$lang = function_exists('bdr_v11_lang') ? bdr_v11_lang() : 'fr';
$u = bdr_v11_ui($lang);
get_header();
$slug = function_exists('bdr_v11_get_current_slug') ? bdr_v11_get_current_slug() : get_post_field('post_name', get_the_ID());

echo '<main id="main" class="site-main" tabindex="-1">';
bdr_v11_localized_breadcrumbs($slug,$lang);

$pages = [
'particuliers'=>[
 ['PARTICULIERS','Des solutions bancaires pensées pour chaque étape de votre vie.','Comptes, moyens de paiement, financement, épargne et services à distance réunis dans un parcours simple.'],
 ['Comptes au quotidien','Choisissez le compte adapté à vos opérations courantes, à vos revenus et à vos besoins en devises.','/comptes-cartes/'],
 ['Financer vos projets','Habitat, automobile ou projet personnel : découvrez les principales familles de financement et leurs modalités.','/credits/'],
 ['Construire votre épargne','Constituez progressivement une épargne disponible ou destinée à un projet futur.','/epargne/'],
 ['Gérer vos services à distance','Consultez les fonctionnalités digitales disponibles et les bonnes pratiques de sécurité.','/banque-en-ligne/'],
],
'comptes-cartes'=>[
 ['COMPTES & MOYENS DE PAIEMENT','Des solutions pour gérer vos opérations au quotidien.','La BDR propose une gamme structurée autour des comptes, des cartes et des services associés.'],
 ['Compte courant','Le compte de référence pour les opérations quotidiennes : versements, retraits, virements et moyens de paiement.','/compte-cheque/'],
 ['Compte en devises','Une solution destinée aux besoins liés à la détention et à la gestion de devises, selon la réglementation applicable.','/compte-devise/'],
 ['Cartes bancaires','Découvrez les usages, services et précautions liés aux cartes de paiement et de retrait.','/cartes-bancaires/'],
 ['Services digitaux','Retrouvez les services à distance et les conseils pour protéger vos accès.','/banque-en-ligne/'],
],
'cartes-bancaires'=>[
 ['CARTES BANCAIRES','Des moyens de paiement pour vos achats, retraits et usages à distance.','Comprendre les différentes familles de cartes, leurs usages et les bonnes pratiques de sécurité.'],
 ['Carte CIB','Une carte interbancaire destinée aux opérations de paiement et de retrait, selon les conditions de la banque.','/carte-cib/'],
 ['Carte Visa','Une solution pour les usages internationaux lorsque les conditions d’éligibilité sont réunies.','/carte-visa/'],
 ['Paiement en ligne','Conseils pour utiliser une carte sur internet et reconnaître les dispositifs de sécurité.','/banque-en-ligne/'],
 ['Opposition et sécurité','Les réflexes à adopter en cas de perte, de vol ou d’opération inhabituelle.','/contact/'],
],
'epargne'=>[
 ['ÉPARGNE','Donnez un objectif à votre épargne.','Des solutions organisées selon la disponibilité recherchée, l’horizon du projet et le profil du client.'],
 ['Épargne disponible','Une réserve accessible pour les besoins courants ou les imprévus.','/epargne-disponible/'],
 ['Épargne projet','Constituez progressivement une enveloppe dédiée à un projet identifié.','/epargne-projet/'],
 ['Épargne jeune','Une approche pédagogique pour accompagner les premiers projets d’épargne.','/epargne-jeune/'],
 ['Bien préparer son épargne','Définissez votre objectif, votre horizon et votre niveau de disponibilité avant de choisir une solution.','/contact/'],
],
'placements'=>[
 ['PLACEMENTS','Organisez votre épargne selon votre horizon.','Découvrez les grandes familles de placements et les points à comparer avant toute décision.'],
 ['Dépôt à terme','Une solution de placement à échéance définie, selon les conditions proposées par la banque.','/depot-terme/'],
 ['Bons de caisse','Un placement encadré par des conditions de durée et de rémunération communiquées lors de la souscription.','/bons-caisse/'],
 ['Comparer les horizons','Disponibilité, durée, rendement et risque sont à considérer ensemble.','/contact/'],
],
'credits'=>[
 ['CRÉDITS','Financez vos projets avec une approche adaptée à votre situation.','Découvrez les grandes familles de financement, les étapes d’étude et les éléments généralement examinés.'],
 ['Crédit immobilier','Pour les projets liés à l’acquisition, à la construction ou à l’aménagement d’un logement, selon les produits disponibles.','/credit-immobilier/'],
 ['Crédit à la consommation','Pour certains projets personnels et équipements, sous réserve d’éligibilité.','/credit-consommation/'],
 ['Crédit automobile','Une solution dédiée au financement d’un véhicule lorsque le produit est disponible et adapté au projet.','/credit-auto/'],
 ['Comprendre une demande de crédit','Montant, durée, apport, revenus, charges et garanties peuvent entrer dans l’étude d’un dossier.','/contact/'],
],
'credit-immobilier'=>[
 ['FINANCEMENT IMMOBILIER','Construire, acheter ou améliorer votre logement.','Une page d’information pour comprendre les étapes d’un financement immobilier et préparer votre dossier.'],
 ['Les projets concernés','Acquisition, construction, travaux ou aménagement : le financement dépend de la nature et du montant du projet.',''],
 ['Ce qui est étudié','Le projet, les revenus, les charges, l’apport éventuel, la durée et les garanties demandées sont examinés selon les règles en vigueur.',''],
 ['Préparer votre dossier','Pièce d’identité, justificatifs de revenus, éléments relatifs au logement et justificatifs du projet peuvent être demandés.',''],
],
'credit-consommation'=>[
 ['CRÉDIT À LA CONSOMMATION','Un financement pour certains projets personnels.','Comprenez le fonctionnement d’un crédit à la consommation avant de déposer une demande.'],
 ['À quoi peut-il servir ?','Selon le produit, il peut accompagner l’acquisition de biens ou le financement d’un projet personnel.',''],
 ['Évaluer votre capacité','Avant toute demande, comparez la mensualité envisagée avec vos revenus et charges récurrents.',''],
 ['Une décision étudiée','Toute demande est soumise aux conditions d’éligibilité, à l’étude du dossier et aux règles de risque applicables.',''],
],
'credit-auto'=>[
 ['CRÉDIT AUTOMOBILE','Financez l’acquisition d’un véhicule selon votre projet.','Une présentation claire des éléments à prévoir avant une demande de financement automobile.'],
 ['Projet','Définissez le véhicule, son prix, votre apport éventuel et le montant à financer.',''],
 ['Durée et mensualité','Une durée plus longue peut modifier le montant de la mensualité et le coût global du financement.',''],
 ['Dossier','Les justificatifs nécessaires sont précisés lors de l’étude du dossier.',''],
],
'entreprises'=>[
 ['ENTREPRISES & PROFESSIONNELS','Une banque partenaire du développement de votre activité.','Comptes, trésorerie, investissement, commerce extérieur et solutions digitales structurent l’offre destinée aux professionnels.'],
 ['Gérer votre activité','Comptes professionnels, moyens de paiement et services bancaires à distance pour les opérations courantes.','/financement/'],
 ['Financer l’investissement','Accompagnez vos projets d’équipement, d’extension ou de développement.','/financement-investissement/'],
 ['Financer l’exploitation','Des solutions pour les besoins de trésorerie liés au cycle d’exploitation.','/financement-exploitation/'],
 ['Commerce extérieur','Accompagnez vos opérations d’importation et d’exportation.','/commerce-exterieur/'],
],
'financement'=>[
 ['FINANCEMENT DES ENTREPRISES','Des solutions pour investir, produire et développer votre activité.','Une approche par besoin permet d’identifier la nature du financement à étudier.'],
 ['Investissement','Acquisition d’équipements, extension, modernisation ou développement de capacité.','/financement-investissement/'],
 ['Exploitation','Besoin de trésorerie et accompagnement du cycle d’exploitation.','/financement-exploitation/'],
 ['Projet structurant','Pour les investissements nécessitant une analyse financière et technique approfondie.','/contact/'],
],
'financement-investissement'=>[
 ['FINANCEMENT D’INVESTISSEMENT','Accompagner les projets qui développent votre entreprise.','Une solution de financement se construit à partir du projet, de son calendrier et de sa capacité de remboursement.'],
 ['Le projet','Décrivez l’investissement, son coût, le calendrier de réalisation et les retombées attendues.',''],
 ['Le montage','L’apport, la durée, les garanties et la capacité de remboursement font partie des éléments étudiés.',''],
 ['Le dossier','Préparez les documents juridiques, financiers, fiscaux et techniques nécessaires à l’étude.',''],
],
'financement-exploitation'=>[
 ['FINANCEMENT D’EXPLOITATION','Accompagner le cycle de votre activité.','Les besoins de trésorerie peuvent varier selon les achats, stocks, délais clients et cycles de production.'],
 ['Analyser le besoin','Identifiez le décalage entre encaissements et décaissements et son caractère ponctuel ou récurrent.',''],
 ['Construire la solution','Le conseiller analyse le besoin, les flux et la situation financière de l’entreprise.',''],
 ['Suivre dans la durée','Le suivi des encours et des flux permet d’adapter l’accompagnement à l’évolution de l’activité.',''],
],
'commerce-exterieur'=>[
 ['COMMERCE EXTÉRIEUR','Accompagner les échanges avec vos partenaires internationaux.','Retrouvez les principales familles d’opérations et les documents généralement associés.'],
 ['Importation','Préparez vos opérations, vos documents commerciaux et les modalités de règlement prévues avec votre fournisseur.',''],
 ['Exportation','Sécurisez le traitement documentaire et le règlement des opérations selon le montage retenu.',''],
 ['Garanties et instruments','Selon le besoin, différentes garanties ou instruments documentaires peuvent être étudiés.',''],
],
'agriculture'=>[
 ['AGRICULTURE & TERRITOIRES','Accompagner les projets qui font vivre les territoires.','Une approche dédiée aux exploitants, professionnels et porteurs de projets liés à l’agriculture et aux activités territoriales.'],
 ['Investir','Financer certains équipements, infrastructures et projets de développement, sous réserve d’éligibilité.',''],
 ['Développer l’exploitation','Adapter les solutions au cycle de production, aux besoins d’exploitation et aux investissements.',''],
 ['Projets territoriaux','Accompagner les initiatives créatrices d’activité et de valeur locale.',''],
],
'finance-islamique'=>[
 ['FINANCE ISLAMIQUE','Des solutions fondées sur les principes de la finance islamique.','Découvrez les principales familles de produits et leur logique économique, sans confondre information et conseil personnalisé.'],
 ['Comptes','Des solutions de compte dont le fonctionnement est présenté selon les principes et conditions applicables.','/mourabaha/'],
 ['Mourabaha','Un mécanisme de financement reposant sur l’acquisition puis la revente d’un actif avec une marge connue selon le contrat.','/mourabaha/'],
 ['Ijara','Une formule fondée sur la mise à disposition d’un actif selon les modalités contractuelles prévues.','/ijara/'],
],
'mourabaha'=>[
 ['MOURABAHA','Comprendre le principe d’un financement Mourabaha.','La Mourabaha repose sur une opération d’achat puis de revente d’un actif avec une marge déterminée au contrat.'],
 ['Étape 1 — Le besoin','Le client identifie le bien ou l’actif correspondant à son projet et transmet les informations nécessaires.',''],
 ['Étape 2 — L’acquisition','Selon le montage retenu, la banque acquiert l’actif puis le revend au client dans le cadre contractuel.',''],
 ['Étape 3 — Le règlement','Le prix convenu est réglé selon l’échéancier prévu au contrat.',''],
],
'ijara'=>[
 ['IJARA','Comprendre le principe d’une solution de financement locative.','L’Ijara repose sur la mise à disposition d’un actif en contrepartie de loyers définis contractuellement.'],
 ['Le bien','Le bien financé et les conditions de mise à disposition sont définis avant la conclusion du contrat.',''],
 ['Les loyers','Le montant et la périodicité sont fixés conformément aux conditions du produit.',''],
 ['Fin du contrat','Les modalités de sortie dépendent du contrat et du produit concerné.',''],
],
'algeriens-residents-etranger'=>[
 ['ALGÉRIENS RÉSIDENTS À L’ÉTRANGER','Rester connecté à vos projets en Algérie.','Des informations sur les comptes, l’épargne, l’investissement et l’accompagnement à distance.'],
 ['Comptes et devises','Découvrez les possibilités de gestion de comptes en fonction de votre situation et de la réglementation.','/comptes-cartes/'],
 ['Investir en Algérie','Préparez vos projets immobiliers, entrepreneuriaux ou patrimoniaux avec un accompagnement adapté.','/credits/'],
 ['Services à distance','Utilisez les canaux digitaux disponibles pour rester informé et suivre vos relations bancaires.','/banque-en-ligne/'],
],
'institutionnels'=>[
 ['INSTITUTIONNELS','Des solutions pour les organismes et acteurs du développement.','Gestion de comptes, financement de projets, accompagnement financier et services adaptés aux besoins institutionnels.'],
 ['Gestion financière','Organisez les flux, encaissements et paiements de votre organisme.',''],
 ['Financement de projets','Étudiez les besoins de financement liés aux infrastructures et projets structurants.',''],
 ['Accompagnement','Un interlocuteur peut analyser les caractéristiques du projet et les modalités d’accompagnement.','/contact/'],
],
'banque-en-ligne'=>[
 ['BANQUE EN LIGNE','Des services bancaires accessibles à distance.','Consultez les fonctionnalités disponibles, les bonnes pratiques de sécurité et les principes de fonctionnement d’un service bancaire digital.'],
 ['Consulter','Suivez les informations de vos comptes et opérations lorsque le service est disponible pour votre profil.',''],
 ['Effectuer des opérations','Certaines fonctionnalités peuvent permettre des virements, téléchargements de relevés ou demandes de services.',''],
 ['Sécuriser vos accès','Ne communiquez jamais vos identifiants, codes ou mots de passe. Utilisez uniquement les canaux officiels.','/contact/'],
],
'la-banque'=>[
 ['LA BANQUE','Une institution tournée vers le développement régional.','Découvrez l’identité, la vocation et les principes de la Banque de Développement Régional.'],
 ['Notre mission','Accompagner les particuliers, les entreprises et les acteurs des territoires dans leurs projets.',''],
 ['Notre gouvernance','Présentation des principes de gouvernance et des responsabilités institutionnelles.','/gouvernance/'],
 ['Nos engagements','Qualité de service, proximité, accompagnement et développement durable.','/engagements/'],
 ['Actualités','Communiqués, événements et informations institutionnelles.','/actualites/'],
],
'gouvernance'=>[
 ['GOUVERNANCE','Une organisation au service d’une banque responsable.','La gouvernance définit les responsabilités, les contrôles et les orientations de l’institution.'],
 ['Organes de décision','Les organes compétents définissent les orientations et suivent leur mise en œuvre.',''],
 ['Contrôle et conformité','Les activités bancaires s’inscrivent dans un cadre réglementaire et de contrôle.',''],
 ['Transparence','Les informations institutionnelles et publications sont organisées pour faciliter l’accès du public.',''],
],
'engagements'=>[
 ['NOS ENGAGEMENTS','Construire une relation bancaire durable.','La BDR place la proximité, la qualité de service et le développement des territoires au cœur de son positionnement.'],
 ['Proximité','Un réseau d’agences et des services digitaux pour rester accessible.','/agences/'],
 ['Accompagnement','Des parcours organisés autour des besoins des particuliers, entreprises et institutions.','/particuliers/'],
 ['Responsabilité','Une attention portée aux projets créateurs de valeur économique et territoriale.','/agriculture/'],
],
'recrutement'=>[
 ['RECRUTEMENT','Construire les compétences de demain.','Découvrez les métiers de la banque et les principes de notre politique de recrutement.'],
 ['Nos métiers','Relation client, finance, risques, conformité, systèmes d’information, fonctions supports et réseau.',''],
 ['Candidatures','Les opportunités ouvertes peuvent être publiées sur cette rubrique.',''],
 ['Stages','Les possibilités de stage dépendent des besoins des équipes et des campagnes de recrutement.','/contact/'],
],
];


$pages += [
'versements-retraits'=>[['COMPTE COURANT · OPÉRATIONS','Versements et retraits','Comprendre les opérations d’alimentation et de retrait du compte.','/versements-retraits/']],
'operations-quotidiennes'=>[['COMPTE COURANT · OPÉRATIONS QUOTIDIENNES','Les opérations qui rythment la gestion de votre compte au quotidien.','Versements, retraits, virements, prélèvements et moyens de paiement sont présentés ici avec les principaux points d’attention.'],['Versements et retraits','Effectuez vos opérations d’alimentation et de retrait selon les canaux et conditions proposés par la banque.',''],['Virements','Préparez vos virements en vérifiant soigneusement le bénéficiaire, le montant et les coordonnées utilisées.','/banque-en-ligne/'],['Prélèvements','Les prélèvements permettent de régler certaines dépenses récurrentes selon les mandats et conditions applicables.',''],['Moyens de paiement','Carte bancaire, chéquier et autres moyens disponibles peuvent compléter l’usage du compte selon votre situation.','/cartes-bancaires/'],['Suivi et sécurité','Consultez régulièrement vos opérations et signalez rapidement toute opération inhabituelle.','/securite-digitale/']],
'compte-cheque'=>[['COMPTE COURANT','Le compte de référence pour vos opérations quotidiennes.','Une présentation des usages d’un compte courant, des opérations courantes et des points à vérifier avant l’ouverture.'],['Opérations quotidiennes','Versements, retraits, virements, prélèvements et moyens de paiement selon les services souscrits.','/operations-quotidiennes/'],['Services associés','Carte, chéquier et services à distance peuvent être associés selon le profil et les conditions du compte.','/cartes-bancaires/'],['Ouverture','L’ouverture nécessite les justificatifs demandés et la validation des conditions contractuelles.','/ouvrir-un-compte/']],
'compte-devise'=>[['COMPTE EN DEVISES','Une solution pour gérer vos opérations en devises selon la réglementation applicable.','Les conditions, devises disponibles et modalités sont communiquées par la banque.'],['À quoi sert-il ?','Il peut répondre à certains besoins de détention, de réception ou de gestion de devises.',''],['Conditions','L’éligibilité et les opérations autorisées dépendent du cadre réglementaire et des conditions du produit.',''],['Conseil','Avant toute opération, vérifiez la devise, les frais éventuels et les conditions applicables.','/contact/']],
'carte-cib'=>[['CARTE CIB','Une carte interbancaire pour les opérations de paiement et de retrait.','Découvrez les usages principaux d’une carte CIB et les réflexes de sécurité associés.'],['Paiement','Utilisation auprès des commerçants équipés de terminaux compatibles, selon les limites prévues.',''],['Retrait','Retrait d’espèces auprès des automates acceptant la carte, selon les conditions applicables.',''],['Sécurité','Conservez votre code confidentiel secret et ne communiquez jamais un code reçu par SMS.','/securite-digitale/']],
'carte-visa'=>[['CARTE VISA','Une solution pour certains usages internationaux.','L’accès à une carte internationale dépend du compte, de l’éligibilité et des conditions en vigueur.'],['Paiements à l’étranger','Utilisez la carte auprès des réseaux et commerçants acceptant Visa, selon les conditions du produit.',''],['Retraits','Les retraits peuvent être soumis à des plafonds et frais selon l’opération.',''],['Avant de partir','Vérifiez les plafonds, la validité de la carte et les moyens de contact en cas de perte.','/contact/']],
'epargne-disponible'=>[['ÉPARGNE DISPONIBLE','Constituer une réserve tout en conservant de la disponibilité.','Une solution d’épargne doit être choisie en fonction de la disponibilité recherchée et des conditions de rémunération applicables.'],['Objectif','Créer une réserve de précaution ou préparer une dépense future.',''],['Disponibilité','Les modalités de retrait dépendent du produit et de ses conditions.',''],['Régularité','Des versements réguliers peuvent faciliter la constitution progressive d’une épargne.','']],
'epargne-projet'=>[['ÉPARGNE PROJET','Préparer une dépense identifiée dans le temps.','Définissez un objectif, une échéance et un effort d’épargne réaliste.'],['Objectif et échéance','Le montant cible et la date prévue permettent d’estimer l’effort d’épargne nécessaire.',''],['Suivi','Contrôlez régulièrement l’avancement de votre épargne par rapport à l’objectif.',''],['Adaptation','Une évolution du projet peut conduire à revoir le rythme ou le support choisi.','']],
'epargne-jeune'=>[['ÉPARGNE JEUNE','Donner de bonnes habitudes financières dès les premières années.','Une approche simple pour apprendre à mettre de côté, suivre un objectif et comprendre la gestion d’un budget.'],['Épargner régulièrement','Même de petits montants peuvent aider à construire une habitude.',''],['Objectifs','Projet scolaire, équipement, permis ou premier voyage : l’objectif donne du sens à l’épargne.',''],['Accompagnement','Les conditions applicables aux mineurs et représentants légaux doivent être vérifiées auprès de la banque.','']],
'depot-terme'=>[['DÉPÔT À TERME','Placer une somme pour une durée définie.','Le dépôt à terme associe une durée contractuelle et des conditions de rémunération communiquées lors de la souscription.'],['Durée','La somme est placée selon la durée prévue au contrat.',''],['Rémunération','Le rendement dépend des conditions proposées pour la période et le montant concernés.',''],['Disponibilité','Un retrait avant l’échéance peut être soumis à des conditions particulières.','']],
'bons-caisse'=>[['BONS DE CAISSE','Un placement à échéance définie.','Les bons de caisse sont souscrits selon des conditions de durée, de rémunération et de remboursement prévues au contrat.'],['Échéance','La date d’échéance est déterminée lors de la souscription.',''],['Rendement','Le rendement applicable est celui communiqué et accepté dans les conditions du placement.',''],['Conseil','Comparez l’échéance avec votre besoin de liquidité avant de souscrire.','']],
'securite-digitale'=>[['SÉCURITÉ DIGITALE','Les bons réflexes pour protéger vos services bancaires.','La sécurité commence par la confidentialité des identifiants et la vigilance face aux messages et sites frauduleux.'],['Ne partagez jamais vos codes','La banque ne vous demande pas de transmettre votre mot de passe, PIN ou code OTP par e-mail ou formulaire.',''],['Vérifiez l’adresse du site','Avant de vous connecter, contrôlez l’adresse du site et évitez les liens reçus dans des messages inattendus.',''],['En cas de doute','Contactez votre banque par un canal officiel et faites opposition rapidement en cas de perte ou de fraude suspectée.','/contact/']],
];


$rich_pages = [
'versements-retraits'=>[
 'title'=>'Versements et retraits','eyebrow'=>'COMPTE COURANT · OPÉRATIONS','intro'=>'Comprendre les opérations de versement et de retrait, leurs usages et les précautions à prendre avant d’effectuer une opération.','audience'=>'Clients disposant d’un compte courant et utilisant les canaux autorisés.','features'=>[
  ['Versement au compte','Alimentez votre compte selon les canaux mis à disposition par la banque et conservez les justificatifs utiles.',''],
  ['Retrait d’espèces','Retirez des espèces dans les points de service et automates autorisés, dans les limites et conditions applicables.','/agences/'],
  ['Vérification de l’opération','Contrôlez le montant, le compte concerné et le justificatif avant de quitter le point de service.','/securite-digitale/'],
  ['Suivi des mouvements','Consultez régulièrement les mouvements du compte et signalez rapidement toute anomalie.','/banque-en-ligne/'],
 ],'for'=>'Clients disposant d’un compte compatible avec les opérations concernées.','docs'=>'Une pièce d’identité, les références du compte et tout justificatif requis peuvent être demandés selon l’opération.'],
'particuliers'=>[
 'title'=>'Particuliers','eyebrow'=>'PARTICULIERS','intro'=>'Une gamme organisée autour de vos besoins quotidiens, de vos projets et de vos objectifs d’épargne.','audience'=>'Particuliers','features'=>[
  ['Comptes bancaires','Gérez vos opérations courantes avec un compte adapté à votre situation.','/comptes-cartes/'],
  ['Cartes bancaires','Payez et retirez avec des moyens de paiement adaptés à vos usages.','/cartes-bancaires/'],
  ['Crédits','Préparez vos projets immobiliers, automobiles ou personnels.','/credits/'],
  ['Épargne & placements','Constituez une réserve ou préparez un objectif à moyen et long terme.','/epargne/'],
  ['Services digitaux','Retrouvez vos services à distance et les bonnes pratiques de sécurité.','/banque-en-ligne/'],
 ],'for'=>'Toute personne souhaitant disposer de services bancaires, de moyens de paiement, d’épargne ou de financement selon son profil et les conditions applicables.','docs'=>'Une pièce d’identité valide, justificatifs d’adresse et de revenus ou documents complémentaires peuvent être demandés selon la démarche.'],
'comptes-bancaires'=>['title'=>'Comptes bancaires','eyebrow'=>'PARTICULIERS · COMPTES','intro'=>'Les comptes qui structurent votre relation bancaire au quotidien.','features'=>[['Compte courant','Pour les opérations quotidiennes, les virements, retraits et moyens de paiement.','/compte-cheque/'],['Compte en devises','Pour les besoins liés à la détention et à la gestion de devises, selon le cadre applicable.','/compte-devise/'],['Épargne','Pour mettre de côté et organiser vos projets dans le temps.','/epargne/']], 'for'=>'Particuliers selon leur situation et le type de compte recherché.','docs'=>'Les justificatifs varient selon le compte et le profil du demandeur.'],
'cartes-bancaires'=>['title'=>'Cartes bancaires','eyebrow'=>'PARTICULIERS · MOYENS DE PAIEMENT','intro'=>'Des solutions de paiement et de retrait pensées pour les usages du quotidien et, selon le produit, pour les déplacements à l’étranger.','features'=>[['Carte CIB','Paiements et retraits sur le réseau compatible, selon les conditions du produit.','/carte-cib/'],['Carte internationale','Pour certains paiements et retraits internationaux lorsque l’éligibilité est réunie.','/carte-visa/'],['Sécurité','Réflexes à adopter pour protéger votre carte et vos données.','/securite-digitale/']], 'for'=>'Clients répondant aux conditions d’éligibilité du compte et de la carte.','docs'=>'Pièces d’identité, compte éligible et éléments nécessaires à l’étude de la demande.'],
'carte-rahati'=>['title'=>'Carte Rahati','eyebrow'=>'PARTICULIERS · CARTE','intro'=>'Une carte pensée pour faciliter certains usages de paiement et de retrait. Consultez les conditions et services associés auprès de la BDR.','features'=>[['Usages','Paiement et retrait selon les fonctionnalités activées et les conditions applicables.',''],['Gestion','Suivi des opérations et conservation des justificatifs utiles.','/banque-en-ligne/'],['Sécurité','Ne communiquez jamais votre code confidentiel et signalez toute opération inhabituelle.','/securite-digitale/']], 'for'=>'Les conditions d’accès dépendent du produit et de la situation du client.','docs'=>'Les documents nécessaires sont communiqués lors de la demande.'],
'carte-internationale'=>['title'=>'Carte internationale','eyebrow'=>'PARTICULIERS · CARTE','intro'=>'Une solution pour certains usages à l’international, sous réserve des conditions d’éligibilité et des règles applicables.','features'=>[['Paiement à l’étranger','Utilisez la carte auprès des commerçants du réseau concerné.',''],['Retrait','Retrait auprès des automates compatibles, dans la limite des conditions prévues.',''],['Avant le départ','Vérifiez validité, plafonds, coordonnées d’assistance et moyens de paiement de secours.','/contact/']], 'for'=>'Clients remplissant les conditions du produit et du compte associé.','docs'=>'La banque précise les justificatifs et conditions lors de la demande.'],
'banque-en-ligne'=>['title'=>'Banque en ligne','eyebrow'=>'SERVICES DIGITAUX','intro'=>'Gérez une partie de vos opérations à distance et retrouvez les informations utiles depuis vos appareils.','features'=>[['Consultation','Accès aux informations disponibles sur vos comptes et opérations selon le service.',''],['Opérations','Certaines demandes et opérations peuvent être disponibles à distance selon le service souscrit.',''],['Sécurité','Protégez vos accès et vérifiez toujours le site ou l’application utilisés.','/securite-digitale/']], 'for'=>'Clients disposant d’un accès au service digital concerné.','docs'=>'Les modalités d’activation et les justificatifs dépendent du service.'],
'services-distance'=>['title'=>'Services bancaires à distance','eyebrow'=>'SERVICES DIGITAUX','intro'=>'Un espace pour consulter et gérer les services bancaires proposés à distance.','features'=>[['Consulter','Visualisez les informations disponibles sur vos comptes.',''],['Gérer','Certaines opérations peuvent être initiées selon les droits et services activés.',''],['Sécuriser','Utilisez uniquement les canaux officiels et gardez vos identifiants confidentiels.','/securite-digitale/']], 'for'=>'Clients disposant d’un accès activé.','docs'=>'Les modalités d’adhésion sont communiquées par la banque.'],
'alertes-sms'=>['title'=>'Alerte SMS','eyebrow'=>'SERVICES DIGITAUX','intro'=>'Recevez des informations et alertes liées aux services disponibles, selon les modalités d’abonnement.','features'=>[['Alertes','Soyez informé des événements couverts par le service.',''],['Suivi','Utilisez les notifications comme un complément et consultez vos canaux officiels.',''],['Vigilance','Une alerte ne doit jamais conduire à communiquer un code confidentiel.','/securite-digitale/']], 'for'=>'Clients pouvant souscrire au service selon les conditions en vigueur.','docs'=>'Les conditions d’adhésion sont précisées lors de la souscription.'],
'location-coffre'=>['title'=>'Location de coffre','eyebrow'=>'PARTICULIERS · SERVICES','intro'=>'Une solution de conservation sécurisée proposée dans les agences disposant du service.','features'=>[['Disponibilité','Le service dépend de l’agence et des compartiments disponibles.','/agences/'],['Accès','Les modalités d’accès sont définies par le contrat et les règles de sécurité de l’agence.',''],['Contrat','Les conditions de location, durée et responsabilité sont présentées avant souscription.','/contact/']], 'for'=>'Clients répondant aux conditions du service dans les agences équipées.','docs'=>'Pièce d’identité et documents contractuels nécessaires à la souscription.'],
'epargne'=>['title'=>'Épargne','eyebrow'=>'PARTICULIERS · ÉPARGNE','intro'=>'Choisissez une solution en fonction de votre objectif, de votre horizon et du niveau de disponibilité recherché.','features'=>[['Épargne disponible','Constituez une réserve accessible selon les conditions du produit.','/epargne-disponible/'],['Épargne projet','Préparez une dépense identifiée avec un objectif clair.','/epargne-projet/'],['Épargne jeune','Accompagnez les premiers projets et habitudes d’épargne.','/epargne-jeune/']], 'for'=>'Particuliers selon leur situation et le produit choisi.','docs'=>'Les justificatifs et modalités dépendent de la solution d’épargne.'],
'credit-immobilier'=>['title'=>'Crédit immobilier','eyebrow'=>'PARTICULIERS · FINANCEMENT','intro'=>'Un parcours de financement destiné aux projets immobiliers, étudié selon la nature du projet et la situation de l’emprunteur.','features'=>[['Acquisition','Financer l’achat d’un logement selon les conditions du produit.',''],['Construction','Accompagner un projet de construction selon le calendrier et les justificatifs requis.',''],['Travaux','Étudier un projet d’amélioration ou d’aménagement lorsque le produit le permet.','']], 'for'=>'Demandeurs répondant aux conditions d’éligibilité et dont le projet peut être financé par le produit.','docs'=>'Pièce d’identité, revenus, charges, éléments du projet, justificatifs du bien et garanties peuvent être demandés.','simulate'=>true],
'credit-consommation'=>['title'=>'Crédit à la consommation','eyebrow'=>'PARTICULIERS · FINANCEMENT','intro'=>'Un financement destiné à certains projets personnels, sous réserve d’éligibilité et d’étude du dossier.','features'=>[['Projet personnel','Accompagner l’acquisition de certains biens ou services.',''],['Montant & durée','Le montant et la durée sont définis selon le projet et l’étude du dossier.',''],['Remboursement','La mensualité dépend notamment du montant, de la durée et des conditions du financement.','']], 'for'=>'Particuliers répondant aux conditions du produit.','docs'=>'Justificatifs d’identité, revenus, charges et éléments relatifs au projet peuvent être demandés.','simulate'=>true],
'credit-auto'=>['title'=>'Crédit automobile','eyebrow'=>'PARTICULIERS · FINANCEMENT','intro'=>'Préparez le financement de votre véhicule en déterminant le budget, l’apport éventuel et la durée souhaitée.','features'=>[['Véhicule','Définissez précisément le véhicule et son coût.',''],['Financement','Déterminez le montant à financer après prise en compte de votre apport.',''],['Dossier','La banque étudie votre capacité de remboursement et les pièces du projet.','']], 'for'=>'Particuliers selon les conditions du produit et l’étude du dossier.','docs'=>'Pièces d’identité, justificatifs de revenus, devis ou documents du véhicule et autres pièces demandées.','simulate'=>true],
'entreprises-comptes-bancaires'=>['title'=>'Comptes entreprises','eyebrow'=>'ENTREPRISES · COMPTES','intro'=>'Des comptes et services adaptés aux opérations courantes des professionnels et entreprises.','features'=>[['Compte d’exploitation','Centraliser les flux de l’activité et les opérations courantes.',''],['Moyens de paiement','Choisir les moyens adaptés aux dépenses et encaissements de l’entreprise.','/carte-affaires/'],['Services à distance','Faciliter le suivi et certaines opérations depuis les canaux digitaux.','/banque-en-ligne/']], 'for'=>'Entreprises, professionnels et organismes selon leur statut et les conditions d’ouverture.','docs'=>'Documents juridiques de l’entreprise, identité des représentants, justificatifs d’activité et éléments demandés lors de l’ouverture.'],
'carte-affaires'=>['title'=>'Carte affaires','eyebrow'=>'ENTREPRISES · MOYENS DE PAIEMENT','intro'=>'Un moyen de paiement destiné à accompagner les dépenses professionnelles selon les paramètres définis avec l’entreprise.','features'=>[['Dépenses professionnelles','Séparer les dépenses liées à l’activité selon l’organisation de l’entreprise.',''],['Pilotage','Conserver les justificatifs et suivre les opérations.',''],['Sécurité','Protéger la carte, les données et signaler rapidement toute anomalie.','/securite-digitale/']], 'for'=>'Entreprises et professionnels selon les conditions d’éligibilité.','docs'=>'Documents de l’entreprise, habilitations et pièces des porteurs selon la demande.'],
'placements-entreprises'=>['title'=>'Placements entreprises','eyebrow'=>'ENTREPRISES · PLACEMENTS','intro'=>'Valorisez une trésorerie disponible en fonction de l’horizon de placement et des besoins de liquidité.','features'=>[['Trésorerie disponible','Identifier le montant pouvant être immobilisé sans gêner l’exploitation.',''],['Horizon','Comparer les solutions selon la durée souhaitée.',''],['Rendement','Les conditions de rémunération sont communiquées au moment de la souscription.','']], 'for'=>'Entreprises disposant d’une trésorerie compatible avec la solution choisie.','docs'=>'Documents de l’entreprise et habilitations des signataires.'],
'financement-investissement'=>['title'=>'Financement d’investissement','eyebrow'=>'ENTREPRISES · FINANCEMENT','intro'=>'Accompagner les projets d’équipement, d’extension, de modernisation ou de développement.','features'=>[['Équipement','Financer certains équipements nécessaires à l’activité.',''],['Extension','Accompagner un projet d’augmentation de capacité.',''],['Modernisation','Soutenir un programme d’amélioration de l’outil de production.','']], 'for'=>'Entreprises dont le projet et la situation répondent aux critères d’étude.','docs'=>'Plan de financement, comptes de l’entreprise, devis, éléments techniques et justificatifs complémentaires.'],
'financement-exploitation'=>['title'=>'Financement d’exploitation','eyebrow'=>'ENTREPRISES · FINANCEMENT','intro'=>'Des solutions destinées à accompagner les besoins de trésorerie liés au cycle d’exploitation.','features'=>[['Cycle d’exploitation','Analyser les décalages entre dépenses, production, facturation et encaissement.',''],['Trésorerie','Identifier le besoin et sa durée.',''],['Suivi','Le financement est suivi en fonction de l’activité et des conditions convenues.','']], 'for'=>'Entreprises présentant un besoin d’exploitation compatible avec la solution étudiée.','docs'=>'États financiers, situation de trésorerie, contrats ou factures et pièces complémentaires selon le dossier.'],
'commerce-exterieur'=>['title'=>'Commerce extérieur','eyebrow'=>'ENTREPRISES · INTERNATIONAL','intro'=>'Des services pour accompagner les opérations d’importation, d’exportation et les flux internationaux.','features'=>[['Domiciliation','Organiser les opérations de commerce extérieur selon le cadre applicable.','/domiciliation/'],['Crédit documentaire','Encadrer une opération commerciale avec les documents et engagements prévus.','/credit-documentaire/'],['Remise documentaire','Gérer la présentation et le traitement des documents commerciaux.','/remise-documentaire/'],['Transfert libre','Traiter certaines opérations selon les règles et justificatifs requis.','/transfert-libre/'],['Garanties internationales','Accompagner certains engagements contractuels à l’international.','/garanties-internationales/']], 'for'=>'Entreprises réalisant des opérations internationales et répondant aux conditions réglementaires et bancaires.','docs'=>'Contrats, factures, documents de transport et pièces réglementaires selon l’opération.'],
'domiciliation'=>['title'=>'Domiciliation bancaire','eyebrow'=>'COMMERCE EXTÉRIEUR','intro'=>'Un cadre de traitement des opérations d’importation et d’exportation nécessitant une domiciliation bancaire.','features'=>[['Dossier','Constituer les documents liés à l’opération commerciale.',''],['Contrôle documentaire','Les pièces sont examinées selon les règles applicables.',''],['Suivi','Conserver les références et justificatifs de l’opération.','']], 'for'=>'Entreprises autorisées à réaliser l’opération concernée.','docs'=>'Documents commerciaux, réglementaires et justificatifs de l’opération.'],
'credit-documentaire'=>['title'=>'Crédit documentaire','eyebrow'=>'COMMERCE EXTÉRIEUR','intro'=>'Un mécanisme documentaire destiné à encadrer certaines opérations commerciales internationales.','features'=>[['Engagement bancaire','Le dispositif repose sur les conditions et documents définis dans l’opération.',''],['Documents','La conformité des documents présentés est un élément central du traitement.',''],['Délais','Les dates et échéances documentaires doivent être suivies avec attention.','']], 'for'=>'Entreprises réalisant une opération internationale compatible avec le produit.','docs'=>'Contrat commercial, facture, documents d’expédition et autres pièces selon la transaction.'],
'remise-documentaire'=>['title'=>'Remise documentaire','eyebrow'=>'COMMERCE EXTÉRIEUR','intro'=>'Une solution de traitement documentaire pour certaines opérations internationales.','features'=>[['Documents commerciaux','Organiser la présentation des documents liés à la marchandise.',''],['Instructions','Les instructions de traitement sont définies dans le dossier.',''],['Suivi','Le suivi des échéances permet de limiter les retards documentaires.','']], 'for'=>'Entreprises réalisant des opérations compatibles avec le service.','docs'=>'Documents commerciaux et d’expédition nécessaires à l’opération.'],
'garanties-internationales'=>['title'=>'Garanties internationales','eyebrow'=>'COMMERCE EXTÉRIEUR','intro'=>'Des solutions destinées à accompagner certains engagements contractuels à l’international.','features'=>[['Engagement','Analyser précisément l’obligation garantie et sa durée.',''],['Documents','Les termes de la garantie doivent correspondre au contrat concerné.',''],['Suivi','Anticiper les échéances et conditions de mainlevée ou d’appel.','']], 'for'=>'Entreprises dont l’opération et le bénéficiaire répondent aux conditions applicables.','docs'=>'Contrat, projet de garantie, documents juridiques et financiers selon l’opération.'],
'transfert-libre'=>['title'=>'Transfert libre','eyebrow'=>'COMMERCE EXTÉRIEUR','intro'=>'Traitement de certains transferts internationaux selon la réglementation, les justificatifs et les conditions bancaires applicables.','features'=>[['Justificatifs','La nature du transfert détermine les pièces à présenter.',''],['Conformité','Les contrôles réglementaires et bancaires sont réalisés avant traitement.',''],['Traçabilité','Conservez les références et documents de l’opération.','']], 'for'=>'Clients professionnels autorisés à effectuer l’opération concernée.','docs'=>'Pièces justificatives et documents réglementaires selon la nature du transfert.'],
'agriculture'=>['title'=>'Agriculture & territoires','eyebrow'=>'ENTREPRISES · TERRITOIRES','intro'=>'Accompagner les investissements agricoles, les activités rurales et les projets qui participent au développement des territoires.','features'=>[['Production agricole','Financer certains besoins liés à la production et aux équipements.',''],['Équipement','Accompagner l’acquisition d’équipements nécessaires à l’activité.',''],['Développement territorial','Soutenir les projets créateurs de valeur et d’activité locale.','']], 'for'=>'Exploitants, entreprises et porteurs de projets selon les dispositifs disponibles.','docs'=>'Documents d’activité, plan de financement, devis et justificatifs du projet.'],
'financement-agriculture'=>['title'=>'Financement agriculture','eyebrow'=>'AGRICULTURE · FINANCEMENT','intro'=>'Des solutions de financement adaptées à certains investissements et besoins du secteur agricole.','features'=>[['Investissement','Équipements, bâtiments ou développement de capacité selon le projet.',''],['Saison','Prendre en compte le cycle économique et les périodes d’activité.',''],['Projet','Présenter un plan d’investissement cohérent et documenté.','']], 'for'=>'Exploitants et entreprises agricoles selon les conditions des dispositifs.','docs'=>'Justificatifs d’activité, devis, plan de financement et pièces du projet.'],
'financement-industrie'=>['title'=>'Financement industrie','eyebrow'=>'ENTREPRISES · INDUSTRIE','intro'=>'Accompagner les investissements industriels, la modernisation et l’augmentation de capacité.','features'=>[['Équipements','Financer certains équipements de production.',''],['Modernisation','Accompagner l’amélioration de l’outil industriel.',''],['Capacité','Étudier les projets d’extension ou de montée en capacité.','']], 'for'=>'Entreprises industrielles selon l’éligibilité et la capacité financière.','docs'=>'Étude économique, devis, comptes, plan de financement et éléments techniques.'],
'financement-peche-aquaculture'=>['title'=>'Financement pêche & aquaculture','eyebrow'=>'ENTREPRISES · SECTEUR MARITIME','intro'=>'Accompagner certains projets d’investissement dans les activités de pêche et d’aquaculture.','features'=>[['Équipement','Besoins matériels et équipements selon le projet.',''],['Développement','Investissements destinés à améliorer ou développer l’activité.',''],['Étude','Analyse du projet, de l’activité et des capacités de remboursement.','']], 'for'=>'Professionnels et entreprises du secteur selon les dispositifs disponibles.','docs'=>'Documents professionnels, devis, autorisations et éléments financiers du projet.'],
'financement-pme-pmi'=>['title'=>'Financement PME / PMI','eyebrow'=>'ENTREPRISES · PME','intro'=>'Des solutions pour accompagner la croissance, l’investissement et les besoins d’exploitation des PME et PMI.','features'=>[['Création & développement','Étudier les besoins de financement d’une entreprise en développement.',''],['Investissement','Financer des équipements ou des extensions.','/financement-investissement/'],['Trésorerie','Accompagner certains besoins du cycle d’exploitation.','/financement-exploitation/']], 'for'=>'PME et PMI selon la situation financière, le projet et les critères d’éligibilité.','docs'=>'Documents juridiques, comptes, prévisionnels, devis et justificatifs du projet.'],
'finance-islamique'=>['title'=>'Finance islamique','eyebrow'=>'FINANCE ISLAMIQUE','intro'=>'Une gamme structurée autour de principes de finance islamique et présentée selon les besoins des particuliers et des professionnels.','features'=>[['Comptes & épargne','Découvrez les solutions de comptes et de livrets disponibles.','/finance-islamique-comptes/'],['Mourabaha','Financements pour certains projets d’acquisition ou d’équipement.','/mourabaha/'],['Ijara','Solutions de financement locatif pour certains équipements ou actifs.','/ijara/']], 'for'=>'Clients et entreprises selon les conditions propres à chaque produit de finance islamique.','docs'=>'Les pièces et conditions sont précisées pour chaque produit.'],
'finance-islamique-comptes'=>['title'=>'Comptes de finance islamique','eyebrow'=>'FINANCE ISLAMIQUE · COMPTES','intro'=>'Des comptes et solutions d’épargne présentés dans le cadre de la finance islamique.','features'=>[['Compte bancaire','Une solution de gestion des opérations selon le produit disponible.',''],['Livrets d’épargne','Des supports destinés à l’épargne selon les conditions applicables.','/livrets-epargne/'],['Information','Les modalités contractuelles doivent être consultées avant souscription.','/contact/']], 'for'=>'Clients répondant aux conditions du produit.','docs'=>'Justificatifs d’identité et documents demandés lors de l’ouverture.'],
'livrets-epargne'=>['title'=>'Livrets d’épargne','eyebrow'=>'FINANCE ISLAMIQUE · ÉPARGNE','intro'=>'Des solutions d’épargne présentées selon les principes et conditions propres à la finance islamique.','features'=>[['Épargne','Constituer progressivement une réserve.',''],['Objectif','Choisir le support en fonction de l’horizon du projet.',''],['Conditions','Les modalités de rémunération et de fonctionnement sont celles du contrat.','']], 'for'=>'Clients éligibles au produit choisi.','docs'=>'Les justificatifs sont précisés lors de l’ouverture.'],
'mourabaha'=>['title'=>'Mourabaha','eyebrow'=>'FINANCE ISLAMIQUE · FINANCEMENT','intro'=>'Un mode de financement dans lequel la banque acquiert un actif puis le revend selon les conditions contractuelles convenues avec le client.','features'=>[['Consommation','Certains biens peuvent être financés selon les conditions du produit.','/mourabaha-consommation/'],['Travaux','Un projet de travaux peut être étudié lorsque le produit le permet.','/mourabaha-travaux/'],['Équipement professionnel','Financer certains équipements nécessaires à l’activité.','/mourabaha-equipements/'],['Agriculture','Des solutions peuvent être proposées pour certains besoins agricoles.','/mourabaha-agriculture/']], 'for'=>'Particuliers et professionnels selon le produit et les critères d’éligibilité.','docs'=>'Pièces d’identité, justificatifs financiers et documents relatifs à l’actif ou au projet.'],
'mourabaha-consommation'=>['title'=>'Mourabaha consommation','eyebrow'=>'FINANCE ISLAMIQUE · PARTICULIERS','intro'=>'Une solution de financement destinée à certains biens de consommation selon les principes et conditions du produit.','features'=>[['Bien financé','Le bien doit répondre aux critères du produit.',''],['Prix & marge','Le contrat précise le prix de revente et les conditions convenues.',''],['Remboursement','Le calendrier des échéances est défini contractuellement.','']], 'for'=>'Particuliers répondant aux conditions d’éligibilité.','docs'=>'Justificatifs d’identité, revenus et document du bien concerné.'],
'mourabaha-travaux'=>['title'=>'Mourabaha travaux','eyebrow'=>'FINANCE ISLAMIQUE · HABITAT','intro'=>'Une solution pour certains projets de travaux, selon les conditions du financement.','features'=>[['Projet','Décrire précisément les travaux et leur coût.',''],['Justificatifs','Devis et documents du projet permettent l’étude.',''],['Contrat','Les conditions du financement sont présentées avant validation.','']], 'for'=>'Particuliers répondant aux conditions du produit.','docs'=>'Devis, justificatifs du logement, identité et éléments financiers.'],
'mourabaha-equipements'=>['title'=>'Mourabaha équipements professionnels','eyebrow'=>'FINANCE ISLAMIQUE · ENTREPRISES','intro'=>'Financer certains équipements professionnels nécessaires au développement de l’activité.','features'=>[['Équipement','Identifier le matériel et son fournisseur.',''],['Projet','Présenter l’utilité économique et le coût de l’investissement.',''],['Étude','La capacité de remboursement et les garanties éventuelles sont analysées.','']], 'for'=>'Professionnels et entreprises selon les conditions du produit.','docs'=>'Devis, documents de l’entreprise, justificatifs financiers et éléments du projet.'],
'mourabaha-agriculture'=>['title'=>'Mourabaha production agricole','eyebrow'=>'FINANCE ISLAMIQUE · AGRICULTURE','intro'=>'Une solution pouvant accompagner certains besoins liés à la production agricole, selon le produit disponible.','features'=>[['Intrants & besoins','Étudier les besoins éligibles liés à l’activité.',''],['Équipement','Accompagner certains investissements agricoles.',''],['Cycle agricole','Tenir compte du calendrier de production et de remboursement.','']], 'for'=>'Exploitants et entreprises agricoles selon les conditions du produit.','docs'=>'Justificatifs d’activité, devis et documents du projet.'],
'ijara'=>['title'=>'Ijara','eyebrow'=>'FINANCE ISLAMIQUE · FINANCEMENT','intro'=>'Des solutions de financement locatif pouvant concerner certains actifs professionnels, selon les conditions du produit.','features'=>[['Matériel roulant','Étudier certains équipements ou véhicules professionnels.','/ijara-materiel-roulant/'],['Médical','Solutions pour certains équipements médicaux selon l’éligibilité.','/ijara-medical/'],['Travaux publics','Financement de certains matériels liés aux activités de travaux publics.','/ijara-travaux-publics/']], 'for'=>'Professionnels et entreprises selon le produit et les conditions d’éligibilité.','docs'=>'Documents de l’entreprise, devis, caractéristiques de l’actif et éléments financiers.'],
'ijara-materiel-roulant'=>['title'=>'Ijara matériel roulant','eyebrow'=>'FINANCE ISLAMIQUE · ENTREPRISES','intro'=>'Une solution de financement locatif pour certains matériels roulants professionnels.','features'=>[['Actif','Identifier précisément le matériel et son usage professionnel.',''],['Durée','Les conditions de location et les échéances sont définies contractuellement.',''],['Dossier','L’entreprise présente son activité, son projet et ses capacités financières.','']], 'for'=>'Entreprises et professionnels éligibles.','docs'=>'Devis, documents de l’entreprise et pièces financières.'],
'ijara-medical'=>['title'=>'Ijara matériel médical','eyebrow'=>'FINANCE ISLAMIQUE · SANTÉ','intro'=>'Une solution pouvant accompagner l’acquisition d’équipements médicaux dans le cadre d’un financement locatif.','features'=>[['Équipement','Définir le matériel, le fournisseur et le coût.',''],['Activité','Présenter le projet et son intégration dans l’activité.',''],['Étude','Le dossier est étudié selon les critères applicables.','']], 'for'=>'Professionnels de santé et structures éligibles selon le produit.','docs'=>'Devis, documents professionnels et éléments financiers du projet.'],
'ijara-travaux-publics'=>['title'=>'Ijara travaux publics','eyebrow'=>'FINANCE ISLAMIQUE · ENTREPRISES','intro'=>'Une solution pouvant financer certains équipements nécessaires aux travaux publics.','features'=>[['Matériel','Identifier le matériel et son usage.',''],['Marchés','Présenter les contrats ou perspectives permettant de documenter le projet.',''],['Étude','Analyser le besoin, le calendrier et la capacité financière.','']], 'for'=>'Entreprises du secteur répondant aux conditions du produit.','docs'=>'Devis, contrats, documents de l’entreprise et justificatifs financiers.'],
'algeriens-residents-etranger'=>['title'=>'Algériens résidents à l’étranger','eyebrow'=>'SERVICES INTERNATIONAUX','intro'=>'Des solutions pour gérer vos projets en Algérie tout en vivant à l’étranger.','features'=>[['Compte & opérations','Identifier les services bancaires adaptés à votre situation.','/comptes-cartes/'],['Projet immobilier','Préparer un projet d’investissement ou de logement selon les conditions disponibles.','/credit-immobilier/'],['Épargne','Organiser une épargne destinée à un projet en Algérie.','/epargne/']], 'for'=>'Algériens résidant à l’étranger selon la réglementation et les conditions des produits.','docs'=>'Pièces d’identité, justificatifs de résidence et documents liés à la demande.'],
'institutionnels'=>['title'=>'Institutionnels','eyebrow'=>'INSTITUTIONNELS','intro'=>'Des solutions et services pour les organismes, institutions et acteurs publics ou assimilés.','features'=>[['Comptes','Organiser les opérations courantes de l’institution.',''],['Trésorerie & placements','Gérer les disponibilités selon les besoins et le cadre applicable.','/placements/'],['Financement','Étudier certains projets structurants selon les dispositifs disponibles.','/financement/']], 'for'=>'Organismes et institutions selon leur statut et les conditions d’accès aux services.','docs'=>'Documents juridiques, habilitations et pièces propres à l’organisme.'],
];

if($lang!=='fr') $rich_pages=bdr_v11_localize_rich_pages($rich_pages,$lang);
/* V12 – localized rich pages. The online-banking page is handled first so it cannot be swallowed by the generic renderer. */
if($slug==='banque-en-ligne'){ bdr_v15_render_online_page($lang); }
elseif($slug==='taux-de-change'){ bdr_v15_render_fx_page($lang); }
elseif($slug==='actualites'){ bdr_v15_render_news_page($lang); }
elseif(isset($rich_pages[$slug])){
  $d=$rich_pages[$slug];
  $sectionTitle=$lang==='ar'?'عرض منظم حسب الاحتياج':($lang==='en'?'Solutions organised around your needs':'L’essentiel en un coup d’œil');
  $sectionIntro=$lang==='ar'?'عرض منظم لفهم المنتج أو الخدمة قبل التواصل.':($lang==='en'?'A structured overview to understand the product or service before contacting BDR.':'Une présentation structurée pour comprendre le produit ou le service avant de contacter la BDR.');
  $audTitle=$lang==='ar'?'لمن هذا الحل؟':($lang==='en'?'Who is this solution for?':'À qui s’adresse cette solution ?');
  $charTitle=$lang==='ar'?'الخصائص والنقاط الواجب الانتباه إليها':($lang==='en'?'Key features and points to consider':'Caractéristiques et points d’attention');
  $docsTitle=$lang==='ar'?'الوثائق الواجب تحضيرها':($lang==='en'?'Documents to prepare':'Pièces à préparer');
  $pathTitle=$lang==='ar'?'مسارك':($lang==='en'?'Your journey':'Votre parcours');
  $faqTitle=$lang==='ar'?'الأسئلة الشائعة':($lang==='en'?'Frequently asked questions':'Questions fréquentes');
  $moreTitle=$lang==='ar'?'تابع الاستكشاف':($lang==='en'?'Go further':'Aller plus loin');
  $docsIntro=$lang==='ar'?'تعتمد القائمة الدقيقة على وضعيتك والمنتج.':($lang==='en'?'The exact list depends on your situation and the product.':'La liste exacte dépend de votre situation et du produit.');
  bdr_page_hero($d['eyebrow'],$d['title'],$d['intro']);
  bdr_section($sectionTitle,$sectionIntro);
  $cards=[]; foreach($d['features'] as $f){$cards[]=[$d['audience']??'BDR',$f[0],$f[2]?:'#caracteristiques',$f[1]];} bdr_cards($cards); bdr_close_section();
  bdr_section($audTitle); echo '<div class="panel prose"><p>'.esc_html($d['for']).'</p></div>'; bdr_close_section();
  $info=$lang==='ar'?[['المشروع أو الحاجة','حدد الهدف والمبلغ والأفق الزمني للإجراء.'],['الشروط','تخضع الأهلية والحدود والتعريفات والشروط للمنتج والوثائق السارية.'],['الدراسة الشخصية','قد تتطلب بعض الطلبات دراسة وضعية العميل ووثائق داعمة.'],['المرافقة','يمكن للمستشار توضيح الشروط وتوجيهك نحو القناة المناسبة.']]:($lang==='en'?[['Project or need','Define the objective, amount and timeframe of your request.'],['Conditions','Eligibility, limits, fees and terms depend on the product and current documents.'],['Personal assessment','Some requests require a review of the customer situation and supporting documents.'],['Support','An adviser can clarify the terms and direct you to the appropriate channel.']]:[['Projet ou besoin','Définissez clairement l’objectif, le montant et l’horizon de votre démarche.'],['Conditions','L’éligibilité, les plafonds, tarifs et modalités sont ceux du produit et des conditions en vigueur.'],['Étude personnalisée','Certaines demandes nécessitent une analyse de la situation du client et des justificatifs.'],['Accompagnement','Un conseiller peut préciser les modalités et orienter vers le service approprié.']]);
  bdr_section($charTitle); bdr_info_grid($info); bdr_close_section();
  bdr_section($docsTitle,$docsIntro); echo '<div class="panel"><ul class="check-list"><li>'.esc_html($d['docs']).'</li><li>'.esc_html($lang==='ar'?'معلومات إضافية عن المشروع أو النشاط عند الحاجة.':($lang==='en'?'Additional project or business information where needed.':'Informations complémentaires sur le projet ou l’activité, lorsque nécessaire.')).'</li><li>'.esc_html($lang==='ar'?'وثائق تعاقدية أو إثباتات خاصة قد تُطلب أثناء الإجراء.':($lang==='en'?'Specific contractual documents or supporting evidence may be requested during the journey.':'Des documents contractuels ou justificatifs spécifiques peuvent être demandés pendant la démarche.')).'</li></ul></div>'; bdr_close_section();
  $steps=$lang==='ar'?[['تحديد الحاجة','حدد المنتج والهدف والمبلغ والموعد المطلوب.'],['تحضير الملف','اجمع الوثائق التي تناسب وضعيتك.'],['التواصل مع BDR','يوضح المستشار الشروط والمسار المناسب.'],['الإتمام','تتم العملية وفق المسار والوثائق التعاقدية.']]:($lang==='en'?[['Define the need','Identify the product, objective, amount and desired timeframe.'],['Prepare the file','Gather documents relevant to your situation.'],['Talk to BDR','An adviser reviews the need and explains applicable terms.'],['Finalise','The process follows the agreed journey and documentation.']]:[['Définir le besoin','Identifiez le produit, l’objectif, le montant et l’échéance souhaitée.'],['Préparer le dossier','Rassemblez les justificatifs correspondant à votre situation.'],['Échanger avec la BDR','Un conseiller vérifie le besoin et précise les conditions applicables.'],['Finaliser','La souscription ou la décision intervient selon le parcours et les documents contractuels.']]);
  bdr_section($pathTitle); bdr_steps($steps); bdr_close_section();
  if(!empty($d['simulate'])){ $simTitle=$lang==='ar'?'محاكي إرشادي':($lang==='en'?'Indicative simulator':'Simulateur indicatif'); $simIntro=$lang==='ar'?'محاكاة تعليمية غير تعاقدية.':($lang==='en'?'Educational, non-contractual simulation.':'Simulation pédagogique non contractuelle.'); bdr_section($simTitle); echo '<div class="simulator panel"><div class="sim-grid"><label>'.esc_html($lang==='ar'?'المبلغ (دج)':($lang==='en'?'Amount (DZD)':'Montant (DA)')).'<input id="bdr-sim-amount" type="number" min="10000" step="10000" value="2000000"></label><label>'.esc_html($lang==='ar'?'المدة (أشهر)':($lang==='en'?'Term (months)':'Durée (mois)')).'<input id="bdr-sim-term" type="number" min="6" max="360" value="60"></label><label>'.esc_html($lang==='ar'?'المعدل السنوي الافتراضي (%)':($lang==='en'?'Hypothetical annual rate (%)':'Taux annuel hypothétique (%)')).'<input id="bdr-sim-rate" type="number" min="0" max="30" step="0.1" value="6"></label></div><div class="sim-result"><span>'.esc_html($lang==='ar'?'القسط الشهري التقريبي':($lang==='en'?'Indicative monthly payment':'Mensualité indicative')).'</span><strong id="bdr-sim-result">—</strong></div><p class="form-note">'.esc_html($simIntro).'</p></div>'; bdr_close_section(); }
  $faq=$lang==='ar'?[['هل المعلومات المعروضة تعاقدية؟','لا. الشروط النهائية تعتمد على المنتج ووضعيتك والوثائق السارية.'],['ما الوثائق المطلوبة؟','تختلف القائمة حسب المنتج ووضعيتك ويتم تأكيدها أثناء الإجراء.'],['هل يمكنني بدء الطلب عبر الإنترنت؟','يمكن إعداد بعض الطلبات أو طلب المعلومات عبر الإنترنت حسب الخدمة.']]:($lang==='en'?[['Is the information contractual?','No. Final terms depend on the product, your situation and current documentation.'],['Which documents are required?','The list depends on the product and your situation and is confirmed during the journey.'],['Can I start online?','Some requests or information journeys can be initiated online, depending on the service.']]:[['Les informations sont-elles contractuelles ?','Non. Les conditions définitives dépendent du produit, de votre situation et des documents en vigueur.'],['Quels documents faut-il fournir ?','La liste dépend du produit et de votre situation et est confirmée lors de la démarche.'],['Puis-je commencer en ligne ?','Certaines demandes ou prises de contact peuvent être préparées en ligne selon le service.']]);
  bdr_section($faqTitle); bdr_faq($faq); bdr_close_section();
  bdr_section($moreTitle); bdr_v11_related([[$u['branches'],bdr_v11_url('agences',$lang),$lang==='ar'?'اكتشف شبكة الوكالات.':($lang==='en'?'Browse the branch network.':'Consultez le réseau et les coordonnées disponibles.')],[$u['open'],bdr_v11_url('ouvrir-un-compte',$lang),$lang==='ar'?'حضّر مسار فتح الحساب.':($lang==='en'?'Prepare your account-opening journey.':'Préparez votre démarche.')],[$u['contact'],bdr_v11_url('contact',$lang),$lang==='ar'?'اطرح سؤالاً على BDR.':($lang==='en'?'Ask BDR a question.':'Posez une question à la BDR.')]]); bdr_close_section(); bdr_v11_localized_bottom($slug,$lang);
}

elseif($lang!=='fr' && isset($pages[$slug])){ $pages=bdr_v11_localize_pages($pages,$lang); $d=$pages[$slug];
  bdr_page_hero($d[0][0],$d[0][1],$d[0][2]);
  bdr_section($lang==='ar'?'عرض منظم حسب الاحتياج':($lang==='en'?'Solutions organised around your needs':'Une offre organisée autour de vos besoins'),'');
  $cards=[]; foreach(array_slice($d,1) as $x){$cards[]=[$d[0][0],$x[0],$x[2]?:'#details',$x[1]];} bdr_cards($cards); bdr_close_section();
  bdr_section($lang==='ar'?'أهم المعلومات':($lang==='en'?'What to review':'Comprendre avant de choisir'));
  bdr_info_grid($lang==='ar'?[['وضوح المعلومات','راجع خصائص المنتج والشروط السارية.'],['الأهلية','قد تختلف الشروط حسب المنتج والوضعية.'],['الوثائق','تُحدد المستندات المطلوبة حسب الإجراء.'],['المرافقة','يمكن للمستشار توضيح المسار المناسب.']]:($lang==='en'?[['Clear information','Review product features and current terms.'],['Eligibility','Conditions may vary by product and situation.'],['Documents','Required documents depend on the journey.'],['Support','A BDR adviser can explain the appropriate process.']]:[['Une information claire','Les caractéristiques et conditions doivent être consultées avant la démarche.'],['Éligibilité','Les conditions peuvent varier selon le produit et la situation.'],['Documents','Les justificatifs sont précisés selon la démarche.'],['Accompagnement','Un conseiller peut préciser le parcours adapté.']])); bdr_close_section();
  if(in_array($slug,array('credits','credit-immobilier','credit-consommation','credit-auto'),true)){ bdr_section($lang==='ar'?'محاكي إرشادي':($lang==='en'?'Indicative simulator':'Simulateur indicatif'),''); echo '<div class="simulator panel"><div class="sim-grid"><label>'.esc_html($lang==='ar'?'المبلغ (دج)':($lang==='en'?'Amount (DZD)':'Montant (DA)')).'<input id="bdr-sim-amount" type="number" min="10000" step="10000" value="2000000"></label><label>'.esc_html($lang==='ar'?'المدة (بالأشهر)':($lang==='en'?'Term (months)':'Durée (mois)')).'<input id="bdr-sim-term" type="number" min="6" max="360" value="60"></label><label>'.esc_html($lang==='ar'?'معدل سنوي افتراضي (%)':($lang==='en'?'Hypothetical annual rate (%)':'Taux annuel hypothétique (%)')).'<input id="bdr-sim-rate" type="number" min="0" max="30" step="0.1" value="6"></label></div><div class="sim-result"><span>'.esc_html($lang==='ar'?'القسط الشهري التقريبي':($lang==='en'?'Indicative monthly payment':'Mensualité indicative')).'</span><strong id="bdr-sim-result">—</strong></div><p class="form-note">'.esc_html($lang==='ar'?'محاكاة تعليمية غير تعاقدية.':($lang==='en'?'Educational, non-contractual simulation.':'Simulation pédagogique non contractuelle.')).'</p></div>'; bdr_close_section(); }
  bdr_section($lang==='ar'?'الأسئلة الشائعة':($lang==='en'?'Frequently asked questions':'Questions fréquentes')); bdr_faq($lang==='ar'?[['هل الشروط المعروضة تعاقدية؟','لا. الشروط النهائية تعتمد على المنتج والوضعية والوثائق السارية.'],['ما الوثائق المطلوبة؟','تختلف القائمة حسب المنتج ووضعيتك.'],['هل يمكن بدء الإجراء عبر الإنترنت؟','قد يمكن إعداد بعض الطلبات عبر الإنترنت قبل الاستكمال.']]:($lang==='en'?[['Are the terms contractual?','No. Final terms depend on the product, your situation and current documentation.'],['Which documents are required?','The list depends on the product and your situation.'],['Can I start online?','Some journeys can be prepared online before finalisation.']]:[['Les conditions sont-elles contractuelles ?','Non. Les conditions définitives dépendent du produit et des documents en vigueur.'],['Quels documents faut-il fournir ?','La liste dépend du produit et de votre situation.'],['Puis-je commencer en ligne ?','Certaines démarches peuvent être préparées en ligne avant finalisation.']]), false); bdr_close_section();
  bdr_section($lang==='ar'?'تابع الاستكشاف':($lang==='en'?'Go further':'Aller plus loin')); bdr_related([[$lang==='ar'?'العثور على وكالة':($lang==='en'?'Find a branch':'Trouver une agence'),'/agences/',$lang==='ar'?'استكشف شبكة الوكالات.':($lang==='en'?'Browse the branch network.':'Consulter le réseau disponible.')],[$lang==='ar'?'فتح حساب':($lang==='en'?'Open an account':'Ouvrir un compte'),'/ouvrir-un-compte/',$lang==='ar'?'حضّر مسار فتح الحساب.':($lang==='en'?'Prepare your account-opening journey.':'Préparer votre démarche.')],[$lang==='ar'?'اتصل بنا':($lang==='en'?'Contact us':'Nous contacter'),'/contact/',$lang==='ar'?'طرح سؤال على BDR.':($lang==='en'?'Ask BDR a question.':'Poser une question à la BDR.')]]); bdr_close_section();
} elseif($slug==='agences') {
  $u=bdr_v11_ui($lang);
  $agency_title = $lang==='ar' ? 'وكالات BDR' : ($lang==='en' ? 'BDR branches' : 'Agences BDR');
  $agency_intro = $lang==='ar' ? 'اعثر على وكالة BDR واستعرض معلومات الاتصال والموقع الجغرافي.' : ($lang==='en' ? 'Find a BDR branch and view available contact and location information.' : 'Trouvez une agence BDR et consultez les coordonnées ainsi que sa localisation.');
  $search_label = $lang==='ar' ? 'البحث عن وكالة' : ($lang==='en' ? 'Search a branch' : 'Rechercher une agence');
  $wilaya_label = $lang==='ar' ? 'الولاية' : ($lang==='en' ? 'Wilaya' : 'Wilaya');
  $count_label = $lang==='ar' ? 'وكالة' : ($lang==='en' ? 'branches' : 'agences');
  $list_title = $lang==='ar' ? 'شبكة الوكالات' : ($lang==='en' ? 'Branch network' : 'Réseau d’agences');
  $map_title = $lang==='ar' ? 'الموقع على الخريطة' : ($lang==='en' ? 'Map location' : 'Localisation sur la carte');
  bdr_page_hero($lang==='ar'?'شبكة BDR':($lang==='en'?'BDR NETWORK':'RÉSEAU BDR'),$agency_title,$agency_intro);
  bdr_section($map_title,$lang==='ar'?'استخدم البحث أو اختر ولاية لتصفية الوكالات المعروضة.':($lang==='en'?'Use the search field or choose a wilaya to filter the displayed branches.':'Utilisez la recherche ou choisissez une wilaya pour filtrer les agences affichées.'));
  echo '<div class="agency-map-layout">';
  echo '<div class="panel agency-map-panel"><div class="agency-filters">';
  echo '<label for="bdr-agency-filter">'.esc_html($search_label).'<input id="bdr-agency-filter" type="search" placeholder="'.esc_attr($lang==='ar'?'اسم الوكالة أو المدينة أو العنوان':($lang==='en'?'Branch, city or address':'Nom de l’agence, ville ou adresse')).'" autocomplete="off"></label>';
  echo '<label for="bdr-agency-wilaya">'.esc_html($wilaya_label).'<select id="bdr-agency-wilaya"><option value="">'.esc_html($lang==='ar'?'كل الولايات':($lang==='en'?'All wilayas':'Toutes les wilayas')).'</option></select></label>';
  echo '<div class="agency-count" id="bdr-agency-count">0 '.esc_html($count_label).'</div></div>';
  echo '<div id="bdr-agency-map" class="bdr-agency-map" role="application" aria-label="'.esc_attr($map_title).'">';
  echo '<div class="map-placeholder"><strong>'.esc_html($map_title).'</strong><p>'.esc_html($lang==='ar'?'جارٍ تحميل الخريطة…':($lang==='en'?'Loading map…':'Chargement de la carte…')).'</p></div>';
  echo '</div></div>';
  echo '<aside class="panel agency-map-panel"><h2>'.esc_html($list_title).'</h2><div id="bdr-agency-list" class="bdr-agency-list"><p class="search-empty">'.esc_html($lang==='ar'?'جارٍ تحميل الوكالات…':($lang==='en'?'Loading branches…':'Chargement des agences…')).'</p></div></aside>';
  echo '</div>';
  bdr_close_section();
  bdr_section($lang==='ar'?'نصائح للعثور على الوكالة':($lang==='en'?'Before visiting a branch':'Avant votre déplacement'));
  echo '<div class="info-grid">';
  echo '<div class="info-box"><strong>'.esc_html($lang==='ar'?'تحقق من العنوان':($lang==='en'?'Check the address':'Vérifiez l’adresse')).'</strong><p>'.esc_html($lang==='ar'?'تحقق من معلومات الوكالة قبل التنقل.':($lang==='en'?'Check the branch information before travelling.':'Vérifiez les informations de l’agence avant votre déplacement.')).'</p></div>';
  echo '<div class="info-box"><strong>'.esc_html($lang==='ar'?'تواصل مع الوكالة':($lang==='en'?'Contact the branch':'Contactez l’agence')).'</strong><p>'.esc_html($lang==='ar'?'استخدم رقم الهاتف المعروض أو قنوات BDR الرسمية.':($lang==='en'?'Use the displayed telephone number or official BDR channels.':'Utilisez le numéro affiché ou les canaux officiels de la BDR.')).'</p></div>';
  echo '<div class="info-box"><strong>'.esc_html($lang==='ar'?'الأمان':($lang==='en'?'Security':'Sécurité')).'</strong><p>'.esc_html($lang==='ar'?'لا ترسل كلمات المرور أو رموز المصادقة عبر نموذج الاتصال.':($lang==='en'?'Never send passwords or authentication codes through a contact form.':'N’envoyez jamais de mot de passe ou de code d’authentification via un formulaire de contact.')).'</p></div>';
  echo '</div>';
  bdr_close_section();
  bdr_v11_localized_bottom($slug,$lang);
} elseif(isset($pages[$slug])){
  $d=$pages[$slug];
  bdr_page_hero($d[0][0],$d[0][1],$d[0][2]);
  bdr_section('Une offre organisée autour de vos besoins','Chaque rubrique présente les usages, les points d’attention et les étapes à connaître avant de contacter un conseiller.');
  $cards=[]; foreach(array_slice($d,1) as $x){$cards[]=[$d[0][0],$x[0],$x[2]?:'#details',$x[1]];} bdr_cards($cards); bdr_close_section();
  bdr_section('Comprendre avant de choisir','Quelques repères utiles pour préparer votre démarche.');
  bdr_info_grid([
   ['Une information claire','Les caractéristiques d’un produit doivent être consultées avec les conditions et tarifs en vigueur.'],
   ['Une étude personnalisée','L’éligibilité et les conditions peuvent dépendre de votre situation et du produit choisi.'],
   ['Des justificatifs','Les pièces à fournir sont précisées selon la nature de la demande.'],
   ['Un accompagnement','Une agence ou un conseiller peut vous orienter vers la solution correspondant à votre besoin.'],
  ]); bdr_close_section();
  if($slug==='credits' || $slug==='credit-immobilier' || $slug==='credit-consommation' || $slug==='credit-auto'){
    bdr_section('Simulateur indicatif','Une première estimation pour comprendre l’ordre de grandeur d’une mensualité.');
    echo '<div class="simulator panel"><div class="sim-grid"><label>Montant (DA)<input id="bdr-sim-amount" type="number" min="10000" step="10000" value="2000000"></label><label>Durée (mois)<input id="bdr-sim-term" type="number" min="6" max="360" step="1" value="60"></label><label>Taux annuel indicatif (%)<input id="bdr-sim-rate" type="number" min="0" max="30" step="0.1" value="6"></label></div><div class="sim-result"><span>Mensualité indicative</span><strong id="bdr-sim-result">—</strong></div><p class="form-note">Simulation pédagogique non contractuelle. Elle ne constitue ni une offre de crédit ni une indication de taux applicable.</p></div>'; bdr_close_section();
  }
  bdr_section('Les prochaines étapes','Quand vous souhaitez aller plus loin, choisissez le parcours adapté.');
  bdr_related([
   ['Trouver une agence','/agences/','Localiser une agence et consulter ses coordonnées.'],
   ['Ouvrir un compte','/ouvrir-un-compte/','Préparer une demande de prise de rendez-vous.'],
   ['Nous contacter','/contact/','Poser une question à l’équipe BDR.'],
  ]); bdr_close_section();
  bdr_section('Questions fréquentes'); bdr_faq([
   ['Les informations présentées sont-elles contractuelles ?','Non. Les conditions définitives dépendent du produit, de votre situation et des documents contractuels en vigueur.'],
   ['Quels documents faut-il fournir ?','La liste dépend du produit et de votre situation. Elle vous est communiquée lors de la démarche.'],
   ['Puis-je commencer en ligne ?','Certaines démarches peuvent être préparées en ligne avant une finalisation selon le parcours concerné.'],
  ]); bdr_close_section();
} elseif($lang!=='fr' && $slug==='ouvrir-un-compte') {
  $c=bdr_v11_special_copy($slug,$lang);
  bdr_page_hero($c['ey'],$c['title'],$c['intro']);
  bdr_section($c['choose']); bdr_cards([[$lang==='ar'?'الأفراد':($lang==='en'?'INDIVIDUALS':'PARTICULIERS'),bdr_v11_title('compte-cheque',$lang),'/'.$lang.'/compte-cheque/',$lang==='ar'?'للمعاملات اليومية ووسائل الدفع.':($lang==='en'?'For everyday transactions and payments.':'Pour les opérations quotidiennes et les moyens de paiement.')],[$lang==='ar'?'الأفراد':($lang==='en'?'INDIVIDUALS':'PARTICULIERS'),bdr_v11_title('compte-devise',$lang),'/'.$lang.'/compte-devise/',$lang==='ar'?'للاحتياجات المرتبطة بالعملات الأجنبية وفق الشروط.':($lang==='en'?'For foreign currency needs, subject to applicable rules.':'Pour les besoins liés à la gestion de devises, selon les règles applicables.')],[$lang==='ar'?'الادخار':($lang==='en'?'SAVINGS':'ÉPARGNE'),bdr_v11_title('epargne',$lang),'/'.$lang.'/epargne/',$lang==='ar'?'لتكوين احتياط أو تحضير مشروع.':($lang==='en'?'To build a reserve or prepare a project.':'Pour constituer une réserve ou préparer un projet.')]]); bdr_close_section();
  bdr_section($c['journey']); bdr_steps($lang==='ar'?[['اختيار الحساب','حدد نوع الحساب الذي يناسب احتياجاتك.'],['تحضير الوثائق','تحقق من الوثائق المطلوبة حسب وضعيتك.'],['اختيار القناة','اختر الوكالة أو القناة المناسبة.'],['الإتمام','تُعرض الشروط قبل التحقق النهائي.']]:($lang==='en'?[['Choose the account','Identify the account that matches your needs.'],['Prepare documents','Check the documents required for your situation.'],['Choose a channel','Select the appropriate branch or channel.'],['Finalise','Terms are presented before final validation.']]:[['Choisir le compte','Identifiez le compte correspondant à votre besoin.'],['Préparer les justificatifs','Vérifiez les pièces nécessaires selon votre situation.'],['Choisir un point de contact','Sélectionnez l’agence ou le canal approprié.'],['Finaliser','Les conditions sont présentées avant validation finale.']])); bdr_close_section();
  bdr_section($c['start']); echo '<div class="cta-band"><div><h2>'.esc_html($c['help']).'</h2><p>'.esc_html($lang==='ar'?'اطلب المعلومات أو اعثر على وكالة.':($lang==='en'?'Request information or find a branch.':'Demandez des informations ou identifiez une agence.')).'</p></div><div><a class="btn btn-primary" href="'.esc_url(bdr_v11_url('contact',$lang)).'">'.esc_html($c['request']).'</a> <a class="btn" href="'.esc_url(bdr_v11_url('agences',$lang)).'">'.esc_html(bdr_v11_ui($lang)['branches']).'</a></div></div>'; bdr_close_section();
} elseif($lang!=='fr' && $slug==='contact') {
  $c=bdr_v11_special_copy($slug,$lang); bdr_page_hero($c['ey'],$c['title'],$c['intro']); bdr_section($c['before'],bdr_v11_ui($lang)['noncontract']); echo '<div class="contact-layout"><div class="panel"><h2>'.esc_html($c['request']).'</h2>'.bdr_v11_localized_contact_form($lang,$c['request']).'</div><div><div class="info-box"><strong>'.esc_html($c['email']).'</strong><p><a class="email-contact" href="mailto:'.esc_attr(bdr_v15_opt('email')).'">'.esc_html(bdr_v15_opt('email')).'</a></p></div><div class="info-box"><strong>'.esc_html($c['branch']).'</strong><p>'.esc_html($lang==='ar'?'استخدم شبكة الوكالات للمسارات التي تتطلب مرافقة.':($lang==='en'?'Use the branch network for requests requiring personal support.':'Utilisez le réseau d’agences pour les démarches nécessitant un accompagnement.')).'</p><a class="link" href="'.esc_url(bdr_v11_url('agences',$lang)).'">'.esc_html(bdr_v11_ui($lang)['branches']).' →</a></div></div></div>'; bdr_close_section();
} elseif($lang!=='fr' && in_array($slug,array('mentions-legales','donnees-personnelles','plan-du-site'),true)){
  if($slug==='mentions-legales'){
    $legal=bdr_v12_legal_sections($lang);
    bdr_page_hero($lang==='ar'?'معلومات قانونية':($lang==='en'?'LEGAL INFORMATION':'INFORMATIONS'),bdr_v11_title($slug,$lang),$legal['intro']);
    foreach($legal['sections'] as $sec){ bdr_section($sec[0]); echo '<div class="panel prose"><p>'.esc_html($sec[1]).'</p></div>'; bdr_close_section(); }
  } elseif($slug==='donnees-personnelles'){
    $p=bdr_v11_profile($slug,$lang); bdr_page_hero($p['eyebrow'],$p['title'],$p['intro']); bdr_section($p['title']); echo '<div class="panel prose">';
    echo '<h3>'.esc_html($lang==='ar'?'مبادئ حماية البيانات':($lang==='en'?'Data protection principles':'Principes de protection')).'</h3><p>'.esc_html($lang==='ar'?'تُستخدم المعلومات المرسلة عبر النماذج لمعالجة الطلب المعني فقط، ولا ترسل بيانات المصادقة البنكية.':($lang==='en'?'Information submitted through forms is used only to process the related request. Never send banking credentials.':'Les informations transmises via les formulaires servent au traitement de la demande correspondante. N’envoyez jamais de données d’authentification bancaire.')).'</p><h3>'.esc_html($lang==='ar'?'حقوقك':($lang==='en'?'Your rights':'Vos droits')).'</h3><p>'.esc_html($lang==='ar'?'يجب تحديد طرق ممارسة الحقوق ومدد الاحتفاظ في السياسة الرسمية.':($lang==='en'?'The official policy should state how rights are exercised and how long information is retained.':'La politique officielle doit préciser les modalités d’exercice des droits et les durées de conservation.')).'</p></div>'; bdr_close_section();
  } else {
    $p=bdr_v11_profile($slug,$lang); bdr_page_hero($p['eyebrow'],$p['title'],$p['intro']); bdr_section($p['title']); echo '<div class="feature-grid">'; foreach(bdr_v11_catalog() as $s=>$r){ if($s==='') continue; echo '<a class="feature" href="'.esc_url(bdr_v11_url($s,$lang)).'"><strong>'.esc_html($r[$lang]).'</strong><span>'.esc_html(bdr_v11_ui($lang)['learn']).'</span></a>'; } echo '</div>'; bdr_close_section();
  }

} elseif($lang==='fr' && $slug==='ouvrir-un-compte'){
  bdr_page_hero('DEVENIR CLIENT','Ouvrir un compte','Préparez votre démarche en quelques étapes. Cette page présente le parcours avant toute prise de contact.');
  bdr_section('Quel compte choisir ?'); bdr_cards([
   ['PARTICULIERS','Compte courant','/compte-cheque/','Pour les opérations quotidiennes et les moyens de paiement.'],
   ['PARTICULIERS','Compte en devises','/compte-devise/','Pour les besoins liés à la gestion de devises, selon les règles applicables.'],
   ['ÉPARGNE','Solutions d’épargne','/epargne/','Pour constituer une réserve ou préparer un projet.'],
  ]); bdr_close_section();
  bdr_section('Le parcours d’ouverture'); bdr_steps([
   ['Choisir le compte','Identifiez le type de compte correspondant à votre besoin.'],
   ['Préparer les justificatifs','La banque vous indiquera les pièces nécessaires selon votre situation.'],
   ['Choisir un point de contact','Une agence peut finaliser la démarche selon le parcours retenu.'],
   ['Finaliser l’ouverture','La convention et les conditions sont présentées avant toute validation.'],
  ]); bdr_close_section();
  bdr_section('Commencer la démarche'); echo '<div class="cta-band"><div><h2>Besoin d’un accompagnement ?</h2><p>Demandez des informations ou identifiez une agence.</p></div><div><a class="btn btn-primary" href="'.esc_url(bdr_v11_url('contact',$lang)).'">Demander des informations</a> <a class="btn" href="'.esc_url(bdr_v11_url('agences',$lang)).'">Trouver une agence</a></div></div>'; bdr_close_section();
} elseif($slug==='contact'){
  bdr_page_hero('RELATION CLIENT','Contactez la BDR','Trouvez le bon canal pour une question sur un produit, une agence ou une démarche.');
  bdr_section('Avant de nous écrire','Les demandes générales peuvent être adressées à l’équipe BDR. N’envoyez jamais de mot de passe, code OTP, PIN ou identifiant bancaire.');
  echo '<div class="contact-layout"><div class="panel"><h2>Votre demande</h2>'.bdr_v3_contact_form('Demande d’information').'</div><div><div class="info-box"><strong>Par e-mail</strong><p><a class="email-contact" href="mailto:'.esc_attr(bdr_v15_opt('email')).'">'.esc_html(bdr_v15_opt('email')).'</a></p></div><div class="info-box"><strong>En agence</strong><p>Utilisez le réseau d’agences pour une démarche nécessitant un accompagnement.</p><a class="link" href="'.esc_url(bdr_v11_url('agences',$lang)).'">Trouver une agence →</a></div></div></div>'; bdr_close_section();
} elseif($slug==='mentions-legales' || $slug==='donnees-personnelles' || $slug==='plan-du-site'){
  if($slug==='mentions-legales'){
    $legal=bdr_v12_legal_sections($lang);
    bdr_page_hero('INFORMATIONS',$lang==='ar'?'الإشعارات القانونية':($lang==='en'?'Legal notice':'Mentions légales'),$legal['intro']);
    foreach($legal['sections'] as $sec){ bdr_section($sec[0]); echo '<div class="panel prose"><p>'.esc_html($sec[1]).'</p></div>'; bdr_close_section(); }
  } elseif($slug==='donnees-personnelles'){
    $p=bdr_v11_profile($slug,$lang); bdr_page_hero($p['eyebrow'],$p['title'],$p['intro']); bdr_section($p['title']); echo '<div class="panel prose"><h3>Responsable du traitement</h3><p>Les coordonnées officielles du responsable du traitement doivent être complétées avant la mise en production définitive.</p><h3>Données collectées</h3><p>Les formulaires peuvent traiter les informations nécessaires à la réponse aux demandes. N’envoyez jamais de données d’authentification bancaire.</p><h3>Finalités et conservation</h3><p>Les finalités, durées de conservation et modalités d’exercice des droits doivent être précisées dans la politique officielle.</p><h3>Sécurité</h3><p>Des mesures techniques et organisationnelles sont mises en œuvre pour limiter les accès non autorisés.</p></div>'; bdr_close_section();
  } else {
    $p=bdr_v11_profile($slug,$lang); bdr_page_hero($p['eyebrow'],$p['title'],$p['intro']); bdr_section($p['title']); echo '<div class="feature-grid">'; foreach(bdr_v11_catalog() as $s=>$r){if($s==='')continue;echo '<a class="feature" href="'.esc_url(bdr_v11_url($s,$lang)).'"><strong>'.esc_html($r[$lang]).'</strong><span>Consulter la rubrique →</span></a>'; } echo '</div>'; bdr_close_section();
  }

} else {
  bdr_page_hero('BDR',get_the_title(),'Retrouvez les informations et services de la Banque de Développement Régional.');
  bdr_section('Contenu'); echo '<div class="panel prose">'; while(have_posts()):the_post();the_content();endwhile; echo '</div>'; bdr_close_section();
}
bdr_bottom_navigation($slug);
echo '</main>';
?>
<?php get_footer(); ?>
